name: tf2.3
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
      - tensorflow==2.3.0
      - protobuf==3.20.3
      - urllib3==1.26.16
      - scikit-image
      - scipy
      - ipython
      - matplotlib
      - numpy
      - pandas
      - pillow
      - tifffile
      - tqdm
      - typing_extensions

